### ISSUE TITLE
[sbd] wyczyszczenie pytań dotyczących RBD w bazie pytań z SBD 

### ISSUE THREAD

**Issue by oskalbarczyk** [bibixx/zdaj-se-pjatk-data#61]
w pytaniach dotyczących przedmiotu SBD powtarzają się pytania z RBD które z tego co wiem nie mają za bardzo szansy na pojawienie się na egzaminie (nie trafiłem na żadne z nich na terminie zerowym oraz pierwszym jak pytałem ludzi na roku to też na nic nie trafili)

**Comment by bibixx** [comment]
Nie chcę zbytnio usuwać pytań. Po pierwsze to może niekoniecznie takie, ale podobne może się kiedyś jeszcze pojawią. Po drugie to nie mam zbytnio mechanizmu na usuwanie pytań ze względu na scrape'owanie z mykhi. 

To co mogę jedynie zaproponować to zostawienie komentarza pod tym pytaniami z informacją że aktualnie nie są te pytania wykorzystywane

**Comment by oskalbarczyk** [comment]
W wersji 3.0 nie ma dostępu do komentarzy czy jest w planach dodanie ich?
Wpadłem teraz na pomysł że mogła by się przydać opcja głosowania czy dane pytanie pojawiło się na egzaminie coś jak na leetcode. Byłaby wtedy opcja np sortowania pytań po tym jak często były "widziane" 
Pozdrawiam :)

**Comment by bibixx** [comment]
Ogólnie komentarze powinny być wspierane, ale się domyślnie nie wyświetlają (jeśli ich nie ma). Na pytaniach powinno być pole `comments`, które trzyma komentarze.

**Comment by bibixx** [comment]
Co do głosowania (i tak w zasadzie komentarzy) problem jest taki, że cała baza danych jest w JSONie na GitHubie (co jest zamierzonym rozwiązaniem). Tak więc jakakolwiek "interaktywna" rzecz jest dość trudna do zrealizowania 😕

Zależy mi na tym żeby wszystko było open source i dostępne w razie gdyby np nie chciało mi się już tego utrzymywać.

Natomiast jeśli masz jakieś propozycje to zapraszam tutaj: https://github.com/bibixx/zdaj-se-pjatk/issues/38
